/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.EventOrganizerRole;

import Business.EcoSystem;
import Business.Network.Network;
import Business.Enterprise.Enterprise;
import Business.Organization.*;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EventWorkRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saikr
 */
public class CreateEventJPanel extends javax.swing.JPanel {
        private JPanel userProcessContainer;
    private  AwarnessCampaign organization;
    private Enterprise enterprise;
        private UserAccount userAccount;
        private EcoSystem system;
    /**
     * Creates new form CreateEventJPanel
     */
    public CreateEventJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise,EcoSystem ecosystem) {
       initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.system = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblEventName = new javax.swing.JLabel();
        jlblVenue = new javax.swing.JLabel();
        jlblHeading = new javax.swing.JLabel();
        txtEvent = new javax.swing.JTextField();
        txtVenue = new javax.swing.JTextField();
        jlblDate = new javax.swing.JLabel();
        jlblTime = new javax.swing.JLabel();
        txtHours = new javax.swing.JTextField();
        txtMinutes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jlblPurpose = new javax.swing.JLabel();
        txtPurpose = new javax.swing.JTextField();
        jlblFunds = new javax.swing.JLabel();
        txtFunds = new javax.swing.JTextField();
        Date = new org.netbeans.modules.form.InvalidComponent();
        txtDate = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jlblEventName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblEventName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblEventName.setText("Event Name:");

        jlblVenue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblVenue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblVenue.setText("Venue:");

        jlblHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblHeading.setForeground(new java.awt.Color(255, 0, 51));
        jlblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHeading.setText("CREATE NEW ORGAN DONATION EVENT");

        txtEvent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtVenue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVenue.setText(" ");
        txtVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVenueActionPerformed(evt);
            }
        });

        jlblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblDate.setText("Date:");

        jlblTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblTime.setText("Time:");

        txtHours.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHours.setText("HH");

        txtMinutes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMinutes.setText("MM");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText(":");

        btnCreate.setBackground(new java.awt.Color(204, 204, 204));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 0, 51));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 51));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jlblPurpose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblPurpose.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblPurpose.setText("Purpose:");

        txtPurpose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlblFunds.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblFunds.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblFunds.setText("Funds Required:");

        txtFunds.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jlblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblEventName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblFunds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblPurpose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblVenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txtMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEvent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtPurpose, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtFunds)
                            .addComponent(txtDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jlblHeading)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblEventName)
                            .addComponent(txtEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblPurpose)
                            .addComponent(txtPurpose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblFunds))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblDate)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlblTime)
                                .addComponent(txtMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblVenue)
                            .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)))
                .addGap(27, 27, 27)
                .addComponent(btnCreate)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Date, btnCreate, jlblDate, jlblEventName, jlblFunds, jlblPurpose, jlblTime, jlblVenue, txtEvent, txtFunds, txtHours, txtMinutes, txtPurpose, txtVenue});

    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String message = txtEvent.getText();
        String venue = txtVenue.getText();
        Date d = (txtDate.getDate());
        Date today = new Date(); 
        String t = txtHours.getText()+":"+txtMinutes.getText();
        EventWorkRequest request = new EventWorkRequest();
        request = (EventWorkRequest) request;
        request.setMessage(message);
        request.setVenue(venue);
        request.setDate(d);
        request.setTime(t);
        request.setStatus("Request Submitted");
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Event Name can't be empty");
            return;
        }
        if(venue.equals("")){
            JOptionPane.showMessageDialog(null, "Venue can't be empty");
            return;
        }
        
        if (!d.after(today)) {
            JOptionPane.showMessageDialog(null, "Please select a proper date");
            return;
        }
        
        
        int hrs=0;
        int min=0;
        try{
            hrs = Integer.parseInt(txtHours.getText());
            min = Integer.parseInt(txtMinutes.getText());
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Please enter only numbers");
         return;
        }
        if(hrs<0 || hrs >=24){
             JOptionPane.showMessageDialog(null, "Hours Should be between 0-23");
             return;
        }
         if(min<0 || min >=60){
             JOptionPane.showMessageDialog(null, "Minutes Should be between 0-60");
             return;
        }
        request.setSender(userAccount);
        request.setMessage(message);
        request.setComment(txtPurpose.getText());
        request.setAmount(txtFunds.getText());
        if(userAccount.getWorkQueue()==null){
            WorkQueue wq = new WorkQueue();
                 userAccount.setWorkQueue(wq);
        }
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        Organization org = null;
        for(Network network:system.getNetworkList()){
        for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
         System.out.println("Sai"+organization.getName());
         if(organization instanceof PoliciesAndFinance){
         System.out.println("Sandeep"+organization.getName()); 
         for (UserAccount ua :organization.getUserAccountDirectory().getUserAccountList()){
                 
                if(organization instanceof PoliciesAndFinance){
       if(ua.getWorkQueue()== null){
                 WorkQueue wq = new WorkQueue();
                 ua.setWorkQueue(wq);}
                    
         ua.getWorkQueue().getWorkRequestList().add(request);
         request.setReceiver(ua);
                break;} }
                    if (organization instanceof AwarnessCampaign) {
                        System.out.println("Organization: "+organization);
                        org= organization;
                        break;
                    }
                }

            }
        }


        if (org != null) {


                   }}
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EventOrganizerWorkAreaJPanel eowajp = (EventOrganizerWorkAreaJPanel ) component;
        eowajp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EventOrganizerWorkAreaJPanel eowajp = (EventOrganizerWorkAreaJPanel ) component;
        eowajp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVenueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.netbeans.modules.form.InvalidComponent Date;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblEventName;
    private javax.swing.JLabel jlblFunds;
    private javax.swing.JLabel jlblHeading;
    private javax.swing.JLabel jlblPurpose;
    private javax.swing.JLabel jlblTime;
    private javax.swing.JLabel jlblVenue;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtEvent;
    private javax.swing.JTextField txtFunds;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtMinutes;
    private javax.swing.JTextField txtPurpose;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
